services:
  projecteuler-java:
    image: projecteuler-java:latest
    build:
      context: .
      target: testing
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info} ## (1) ## info | debug
      BRUTEFORCE: ${BRUTEFORCE:-false} ## (1) ## true | false
    volumes:
      - ./build:/app/build
    profiles: ["testing"]

  projecteuler-java-dev:
    image: projecteuler-java:dev
    build:
      context: .
      target: development
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info} ## (1) ## info | debug
      BRUTEFORCE: ${BRUTEFORCE:-false} ## (1) ## true | false
    volumes:
      - ./:/app
    profiles: ["development"]

## REFERENCES:
## (1) Passing Environment variable with fallback value:
##    https://stackoverflow.com/a/70772707/6366150
##
